server:
  port: 8081
  servlet:
    context-path: /user

spring:
  application:
    name: msc-user
  
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/multishop_user?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: UserHikariCP
  
  # Redis配置
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: 0
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
  
  # Jackson配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

# MyBatis Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
    banner: false
  mapper-locations: classpath*:mapper/**/*.xml

# JWT配置
jwt:
  secret: ${JWT_SECRET:MultiShopCoreUserModuleSecretKey2024}
  access-token-expiration: 7200000  # 2小时
  refresh-token-expiration: 604800000  # 7天
  issuer: MultiShopCore

# 验证码配置
verify-code:
  sms:
    expire-time: 300  # 5分钟
    send-limit: 5     # 每日发送限制
  email:
    expire-time: 600  # 10分钟
    send-limit: 10    # 每日发送限制

# 文件存储配置
file:
  upload:
    path: ${FILE_UPLOAD_PATH:/tmp/uploads}
    avatar:
      max-size: 5MB
      allowed-types: jpg,jpeg,png,gif

# 日志配置
logging:
  level:
    com.msc: debug
    org.springframework.security: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/msc-user.log

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# Swagger配置
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  info:
    title: MultiShop Core - User Module API
    description: 用户模块API文档
    version: 1.0.0
    contact:
      name: MultiShop Core Team
      email: team@multishop.com